name: Build and Release (Linux)

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential freeglut3-dev libglu1-mesa-dev libgl1-mesa-dev

      - name: Build project
        run: make

      - name: Archive binary
        run: |
          mkdir -p dist
          cp ./julia dist/
          chmod +x dist/julia
          tar -czf julia-linux.tar.gz -C dist julia

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: julia-linux
          path: julia-linux.tar.gz

  release:
    name: Release Binary
    needs: build-linux
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: julia-linux
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: julia-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
